
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-20T11:24:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3735a5a6dbe185264337360c5b8a6f8d2162fe63",
 "version": "1.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
