"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.entity.fabric_activity_pb2
import layerapi.api.ids_pb2
import layerapi.api.value.balance_operation_result_pb2
import layerapi.api.value.credit_action_category_pb2
import layerapi.api.value.credit_log_event_v2_pb2
import layerapi.api.value.daily_credits_difference_pb2
import layerapi.api.value.date_pb2
import layerapi.api.value.idempotence_key_pb2
import layerapi.api.value.year_month_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class GetCreditLogV2Request(google.protobuf.message.Message):
    """v2"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class TimeFilter(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        DAY_FIELD_NUMBER: builtins.int
        @property
        def day(self) -> api.value.date_pb2.Date: ...
        def __init__(self,
            *,
            day: typing.Optional[api.value.date_pb2.Date] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["day",b"day","filter",b"filter"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["day",b"day","filter",b"filter"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["filter",b"filter"]) -> typing.Optional[typing_extensions.Literal["day"]]: ...

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    TIME_FILTER_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    @property
    def time_filter(self) -> global___GetCreditLogV2Request.TimeFilter: ...
    def __init__(self,
        *,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        time_filter: typing.Optional[global___GetCreditLogV2Request.TimeFilter] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id","time_filter",b"time_filter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id","time_filter",b"time_filter"]) -> None: ...
global___GetCreditLogV2Request = GetCreditLogV2Request

class GetCreditLogV2Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.value.credit_log_event_v2_pb2.CreditLogEventV2]: ...
    def __init__(self,
        *,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        events: typing.Optional[typing.Iterable[api.value.credit_log_event_v2_pb2.CreditLogEventV2]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id","events",b"events"]) -> None: ...
global___GetCreditLogV2Response = GetCreditLogV2Response

class RecordBillableActivityRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    FABRIC_ACTIVITY_FIELD_NUMBER: builtins.int
    IDEMPOTENCE_KEY_FIELD_NUMBER: builtins.int
    LAST_RECORD_FOR_ACTIVITY_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    @property
    def fabric_activity(self) -> api.entity.fabric_activity_pb2.FabricActivity: ...
    @property
    def idempotence_key(self) -> api.value.idempotence_key_pb2.IdempotenceKey: ...
    last_record_for_activity: builtins.bool
    def __init__(self,
        *,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        fabric_activity: typing.Optional[api.entity.fabric_activity_pb2.FabricActivity] = ...,
        idempotence_key: typing.Optional[api.value.idempotence_key_pb2.IdempotenceKey] = ...,
        last_record_for_activity: builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id","billable_activity",b"billable_activity","fabric_activity",b"fabric_activity","idempotence_key",b"idempotence_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id","billable_activity",b"billable_activity","fabric_activity",b"fabric_activity","idempotence_key",b"idempotence_key","last_record_for_activity",b"last_record_for_activity"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["billable_activity",b"billable_activity"]) -> typing.Optional[typing_extensions.Literal["fabric_activity"]]: ...
global___RecordBillableActivityRequest = RecordBillableActivityRequest

class RecordBillableActivityResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> api.value.balance_operation_result_pb2.BalanceOperationResult: ...
    def __init__(self,
        *,
        result: typing.Optional[api.value.balance_operation_result_pb2.BalanceOperationResult] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result"]) -> None: ...
global___RecordBillableActivityResponse = RecordBillableActivityResponse

class SetBalanceToFreeAllowanceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    IDEMPOTENCE_KEY_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    @property
    def idempotence_key(self) -> api.value.idempotence_key_pb2.IdempotenceKey: ...
    def __init__(self,
        *,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        idempotence_key: typing.Optional[api.value.idempotence_key_pb2.IdempotenceKey] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id","idempotence_key",b"idempotence_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id","idempotence_key",b"idempotence_key"]) -> None: ...
global___SetBalanceToFreeAllowanceRequest = SetBalanceToFreeAllowanceRequest

class SetBalanceToFreeAllowanceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> api.value.balance_operation_result_pb2.BalanceOperationResult: ...
    def __init__(self,
        *,
        result: typing.Optional[api.value.balance_operation_result_pb2.BalanceOperationResult] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result"]) -> None: ...
global___SetBalanceToFreeAllowanceResponse = SetBalanceToFreeAllowanceResponse

class RefillAllBalancesUpToFreeAllowanceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDEMPOTENCE_KEY_FIELD_NUMBER: builtins.int
    @property
    def idempotence_key(self) -> api.value.idempotence_key_pb2.IdempotenceKey: ...
    def __init__(self,
        *,
        idempotence_key: typing.Optional[api.value.idempotence_key_pb2.IdempotenceKey] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["idempotence_key",b"idempotence_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["idempotence_key",b"idempotence_key"]) -> None: ...
global___RefillAllBalancesUpToFreeAllowanceRequest = RefillAllBalancesUpToFreeAllowanceRequest

class RefillAllBalancesUpToFreeAllowanceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BALANCES_REFILLED_COUNT_FIELD_NUMBER: builtins.int
    balances_refilled_count: builtins.int
    def __init__(self,
        *,
        balances_refilled_count: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["balances_refilled_count",b"balances_refilled_count"]) -> None: ...
global___RefillAllBalancesUpToFreeAllowanceResponse = RefillAllBalancesUpToFreeAllowanceResponse

class FundBalanceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    IDEMPOTENCE_KEY_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    amount: typing.Text
    @property
    def idempotence_key(self) -> api.value.idempotence_key_pb2.IdempotenceKey: ...
    def __init__(self,
        *,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        amount: typing.Text = ...,
        idempotence_key: typing.Optional[api.value.idempotence_key_pb2.IdempotenceKey] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id","idempotence_key",b"idempotence_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id","amount",b"amount","idempotence_key",b"idempotence_key"]) -> None: ...
global___FundBalanceRequest = FundBalanceRequest

class FundBalanceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> api.value.balance_operation_result_pb2.BalanceOperationResult: ...
    def __init__(self,
        *,
        result: typing.Optional[api.value.balance_operation_result_pb2.BalanceOperationResult] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result"]) -> None: ...
global___FundBalanceResponse = FundBalanceResponse

class GetMonthlyBillingReportRequest(google.protobuf.message.Message):
    """v1"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    YEAR_MONTH_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    @property
    def year_month(self) -> api.value.year_month_pb2.YearMonth: ...
    category: api.value.credit_action_category_pb2.CreditActionCategory.ValueType
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    def __init__(self,
        *,
        year_month: typing.Optional[api.value.year_month_pb2.YearMonth] = ...,
        category: api.value.credit_action_category_pb2.CreditActionCategory.ValueType = ...,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id","year_month",b"year_month"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id","category",b"category","year_month",b"year_month"]) -> None: ...
global___GetMonthlyBillingReportRequest = GetMonthlyBillingReportRequest

class GetMonthlyBillingReportResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REPORTS_FIELD_NUMBER: builtins.int
    @property
    def reports(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.value.daily_credits_difference_pb2.DailyCreditsDifference]: ...
    def __init__(self,
        *,
        reports: typing.Optional[typing.Iterable[api.value.daily_credits_difference_pb2.DailyCreditsDifference]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["reports",b"reports"]) -> None: ...
global___GetMonthlyBillingReportResponse = GetMonthlyBillingReportResponse

class GetCreditsBalanceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    def __init__(self,
        *,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id"]) -> None: ...
global___GetCreditsBalanceRequest = GetCreditsBalanceRequest

class GetCreditsBalanceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CREDITS_BALANCE_FIELD_NUMBER: builtins.int
    credits_balance: typing.Text
    def __init__(self,
        *,
        credits_balance: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["credits_balance",b"credits_balance"]) -> None: ...
global___GetCreditsBalanceResponse = GetCreditsBalanceResponse

class GetWeeklyUsageReportRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    def __init__(self,
        *,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id"]) -> None: ...
global___GetWeeklyUsageReportRequest = GetWeeklyUsageReportRequest

class GetWeeklyUsageReportResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    CREDITS_USED_FIELD_NUMBER: builtins.int
    CREDITS_ADDED_FIELD_NUMBER: builtins.int
    @property
    def start_date(self) -> api.value.date_pb2.Date: ...
    @property
    def end_date(self) -> api.value.date_pb2.Date: ...
    credits_used: typing.Text
    credits_added: typing.Text
    def __init__(self,
        *,
        start_date: typing.Optional[api.value.date_pb2.Date] = ...,
        end_date: typing.Optional[api.value.date_pb2.Date] = ...,
        credits_used: typing.Text = ...,
        credits_added: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end_date",b"end_date","start_date",b"start_date"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["credits_added",b"credits_added","credits_used",b"credits_used","end_date",b"end_date","start_date",b"start_date"]) -> None: ...
global___GetWeeklyUsageReportResponse = GetWeeklyUsageReportResponse
