"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import layerapi.api.service.probe.probe_api_pb2
import grpc

class ProbeAPIStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Probe: grpc.UnaryUnaryMultiCallable[
        api.service.probe.probe_api_pb2.ProbeRequest,
        api.service.probe.probe_api_pb2.ProbeResponse]
    """Checks to see if a server is healthy and ready to serve requests.
    As part of this, a server's dependendent services (internal, e.g. RDS, or external, e.g. Auth0) are also healthy.
    """


class ProbeAPIServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Probe(self,
        request: api.service.probe.probe_api_pb2.ProbeRequest,
        context: grpc.ServicerContext,
    ) -> api.service.probe.probe_api_pb2.ProbeResponse:
        """Checks to see if a server is healthy and ready to serve requests.
        As part of this, a server's dependendent services (internal, e.g. RDS, or external, e.g. Auth0) are also healthy.
        """
        pass


def add_ProbeAPIServicer_to_server(servicer: ProbeAPIServicer, server: grpc.Server) -> None: ...
