
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-23T09:46:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "944e098c52cbb90899bcbe378ca3a635b9ee7b85",
 "version": "2764"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
