# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/activity_wrapper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.api import ids_pb2 as api_dot_ids__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!api/entity/activity_wrapper.proto\x12\x03\x61pi\x1a\rapi/ids.proto\"x\n\x0f\x41\x63tivityWrapper\x12/\n\x10\x64\x61taset_build_id\x18\x01 \x01(\x0b\x32\x13.api.DatasetBuildIdH\x00\x12+\n\x0emodel_train_id\x18\x02 \x01(\x0b\x32\x11.api.ModelTrainIdH\x00\x42\x07\n\x05valueB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_ACTIVITYWRAPPER = DESCRIPTOR.message_types_by_name['ActivityWrapper']
ActivityWrapper = _reflection.GeneratedProtocolMessageType('ActivityWrapper', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVITYWRAPPER,
  '__module__' : 'api.entity.activity_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:api.ActivityWrapper)
  })
_sym_db.RegisterMessage(ActivityWrapper)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _ACTIVITYWRAPPER._serialized_start=57
  _ACTIVITYWRAPPER._serialized_end=177
# @@protoc_insertion_point(module_scope)
