"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.ids_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AnalysisType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _AnalysisTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AnalysisType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ANALYSIS_TYPE_INVALID: _AnalysisType.ValueType  # 0
    ANALYSIS_TYPE_TABLE: _AnalysisType.ValueType  # 1
    ANALYSIS_TYPE_PCCHART: _AnalysisType.ValueType  # 2
class AnalysisType(_AnalysisType, metaclass=_AnalysisTypeEnumTypeWrapper):
    pass

ANALYSIS_TYPE_INVALID: AnalysisType.ValueType  # 0
ANALYSIS_TYPE_TABLE: AnalysisType.ValueType  # 1
ANALYSIS_TYPE_PCCHART: AnalysisType.ValueType  # 2
global___AnalysisType = AnalysisType


class AnalysisTabConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CREATED_BY_ID_FIELD_NUMBER: builtins.int
    CREATED_TIMESTAMP_FIELD_NUMBER: builtins.int
    UPDATED_TIMESTAMP_FIELD_NUMBER: builtins.int
    INPUT_FILTER_FIELD_NUMBER: builtins.int
    ANALYSIS_TYPE_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    SORT_ORDER_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.AnalysisTabConfigurationId: ...
    @property
    def project_id(self) -> api.ids_pb2.ProjectId: ...
    name: typing.Text
    @property
    def created_by_id(self) -> api.ids_pb2.UserId: ...
    created_timestamp: builtins.int
    updated_timestamp: builtins.int
    input_filter: typing.Text
    analysis_type: global___AnalysisType.ValueType
    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def sort_order(self) -> global___FieldSortOrder: ...
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.AnalysisTabConfigurationId] = ...,
        project_id: typing.Optional[api.ids_pb2.ProjectId] = ...,
        name: typing.Text = ...,
        created_by_id: typing.Optional[api.ids_pb2.UserId] = ...,
        created_timestamp: builtins.int = ...,
        updated_timestamp: builtins.int = ...,
        input_filter: typing.Text = ...,
        analysis_type: global___AnalysisType.ValueType = ...,
        fields: typing.Optional[typing.Iterable[typing.Text]] = ...,
        sort_order: typing.Optional[global___FieldSortOrder] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_by_id",b"created_by_id","id",b"id","project_id",b"project_id","sort_order",b"sort_order"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["analysis_type",b"analysis_type","created_by_id",b"created_by_id","created_timestamp",b"created_timestamp","fields",b"fields","id",b"id","input_filter",b"input_filter","name",b"name","project_id",b"project_id","sort_order",b"sort_order","updated_timestamp",b"updated_timestamp"]) -> None: ...
global___AnalysisTabConfiguration = AnalysisTabConfiguration

class FieldSortOrder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FIELD_FIELD_NUMBER: builtins.int
    ASCENDING_FIELD_NUMBER: builtins.int
    field: typing.Text
    ascending: builtins.bool
    def __init__(self,
        *,
        field: typing.Text = ...,
        ascending: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ascending",b"ascending","field",b"field"]) -> None: ...
global___FieldSortOrder = FieldSortOrder
