# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi/entity/image.proto\x12\x03\x61pi\x1a\x17validate/validate.proto\"$\n\x05Image\x12\x1b\n\x08\x64\x61ta_url\x18\x01 \x01(\tB\t\xfa\x42\x06r\x04\x18\x80\xe0]B\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_IMAGE = DESCRIPTOR.message_types_by_name['Image']
Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'api.entity.image_pb2'
  # @@protoc_insertion_point(class_scope:api.Image)
  })
_sym_db.RegisterMessage(Image)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _IMAGE.fields_by_name['data_url']._options = None
  _IMAGE.fields_by_name['data_url']._serialized_options = b'\372B\006r\004\030\200\340]'
  _IMAGE._serialized_start=56
  _IMAGE._serialized_end=92
# @@protoc_insertion_point(module_scope)
