"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.entity.task_pb2
import layerapi.api.ids_pb2
import layerapi.api.value.language_version_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ExecutionPlan(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OPERATIONS_FIELD_NUMBER: builtins.int
    @property
    def operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Operation]: ...
    def __init__(self,
        *,
        operations: typing.Optional[typing.Iterable[global___Operation]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["operations",b"operations"]) -> None: ...
global___ExecutionPlan = ExecutionPlan

class Operation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SEQUENTIAL_FIELD_NUMBER: builtins.int
    PARALLEL_FIELD_NUMBER: builtins.int
    @property
    def sequential(self) -> global___SequentialOperation: ...
    @property
    def parallel(self) -> global___ParallelOperation: ...
    def __init__(self,
        *,
        sequential: typing.Optional[global___SequentialOperation] = ...,
        parallel: typing.Optional[global___ParallelOperation] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["operation",b"operation","parallel",b"parallel","sequential",b"sequential"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["operation",b"operation","parallel",b"parallel","sequential",b"sequential"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["operation",b"operation"]) -> typing.Optional[typing_extensions.Literal["sequential","parallel"]]: ...
global___Operation = Operation

class SequentialOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FEATURE_SET_BUILD_FIELD_NUMBER: builtins.int
    MODEL_TRAIN_FIELD_NUMBER: builtins.int
    DATASET_BUILD_FIELD_NUMBER: builtins.int
    FUNCTION_EXECUTION_FIELD_NUMBER: builtins.int
    @property
    def feature_set_build(self) -> global___UnsupportedOperation: ...
    @property
    def model_train(self) -> global___ModelTrainOperation: ...
    @property
    def dataset_build(self) -> global___DatasetBuildOperation: ...
    @property
    def function_execution(self) -> global___FunctionExecutionOperation: ...
    def __init__(self,
        *,
        feature_set_build: typing.Optional[global___UnsupportedOperation] = ...,
        model_train: typing.Optional[global___ModelTrainOperation] = ...,
        dataset_build: typing.Optional[global___DatasetBuildOperation] = ...,
        function_execution: typing.Optional[global___FunctionExecutionOperation] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dataset_build",b"dataset_build","feature_set_build",b"feature_set_build","function_execution",b"function_execution","model_train",b"model_train","operation",b"operation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dataset_build",b"dataset_build","feature_set_build",b"feature_set_build","function_execution",b"function_execution","model_train",b"model_train","operation",b"operation"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["operation",b"operation"]) -> typing.Optional[typing_extensions.Literal["feature_set_build","model_train","dataset_build","function_execution"]]: ...
global___SequentialOperation = SequentialOperation

class ParallelOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FEATURE_SET_BUILD_FIELD_NUMBER: builtins.int
    MODEL_TRAIN_FIELD_NUMBER: builtins.int
    DATASET_BUILD_FIELD_NUMBER: builtins.int
    FUNCTION_EXECUTION_FIELD_NUMBER: builtins.int
    @property
    def feature_set_build(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UnsupportedOperation]: ...
    @property
    def model_train(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelTrainOperation]: ...
    @property
    def dataset_build(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DatasetBuildOperation]: ...
    @property
    def function_execution(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FunctionExecutionOperation]: ...
    def __init__(self,
        *,
        feature_set_build: typing.Optional[typing.Iterable[global___UnsupportedOperation]] = ...,
        model_train: typing.Optional[typing.Iterable[global___ModelTrainOperation]] = ...,
        dataset_build: typing.Optional[typing.Iterable[global___DatasetBuildOperation]] = ...,
        function_execution: typing.Optional[typing.Iterable[global___FunctionExecutionOperation]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dataset_build",b"dataset_build","feature_set_build",b"feature_set_build","function_execution",b"function_execution","model_train",b"model_train"]) -> None: ...
global___ParallelOperation = ParallelOperation

class UnsupportedOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___UnsupportedOperation = UnsupportedOperation

class ModelTrainOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODEL_VERSION_ID_FIELD_NUMBER: builtins.int
    DEPENDENCY_FIELD_NUMBER: builtins.int
    @property
    def model_version_id(self) -> api.ids_pb2.ModelVersionId: ...
    @property
    def dependency(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """dependencies is a list of operations that must be completed before this operation can be run.
        Each dependency is specified by the fully qualified name of the depended-on entity.
        """
        pass
    def __init__(self,
        *,
        model_version_id: typing.Optional[api.ids_pb2.ModelVersionId] = ...,
        dependency: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["model_version_id",b"model_version_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dependency",b"dependency","model_version_id",b"model_version_id"]) -> None: ...
global___ModelTrainOperation = ModelTrainOperation

class DatasetBuildOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATASET_NAME_FIELD_NUMBER: builtins.int
    DEPENDENCY_FIELD_NUMBER: builtins.int
    dataset_name: typing.Text
    @property
    def dependency(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """dependencies is a list of operations that must be completed before this operation can be run.
        Each dependency is specified by the fully qualified name of the depended-on entity.
        """
        pass
    def __init__(self,
        *,
        dataset_name: typing.Text = ...,
        dependency: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dataset_name",b"dataset_name","dependency",b"dependency"]) -> None: ...
global___DatasetBuildOperation = DatasetBuildOperation

class FunctionExecutionOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ASSET_NAME_FIELD_NUMBER: builtins.int
    TASK_TYPE_FIELD_NUMBER: builtins.int
    FABRIC_FIELD_NUMBER: builtins.int
    EXECUTABLE_PACKAGE_URL_FIELD_NUMBER: builtins.int
    DEPENDENCY_FIELD_NUMBER: builtins.int
    LANGUAGE_VERSION_FIELD_NUMBER: builtins.int
    asset_name: typing.Text
    task_type: api.entity.task_pb2.Task.Type.ValueType
    fabric: typing.Text
    executable_package_url: typing.Text
    @property
    def dependency(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """dependencies is an optional  list of operations that must be completed before this operation can be run.
        Each dependency is specified by the fully qualified name of the depended-on entity.
        """
        pass
    @property
    def language_version(self) -> api.value.language_version_pb2.LanguageVersion: ...
    def __init__(self,
        *,
        asset_name: typing.Text = ...,
        task_type: api.entity.task_pb2.Task.Type.ValueType = ...,
        fabric: typing.Text = ...,
        executable_package_url: typing.Text = ...,
        dependency: typing.Optional[typing.Iterable[typing.Text]] = ...,
        language_version: typing.Optional[api.value.language_version_pb2.LanguageVersion] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["language_version",b"language_version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset_name",b"asset_name","dependency",b"dependency","executable_package_url",b"executable_package_url","fabric",b"fabric","language_version",b"language_version","task_type",b"task_type"]) -> None: ...
global___FunctionExecutionOperation = FunctionExecutionOperation
