"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.entity.run_metadata_entry_pb2
import layerapi.api.ids_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class RunMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RUN_ID_FIELD_NUMBER: builtins.int
    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def run_id(self) -> api.ids_pb2.RunId: ...
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.entity.run_metadata_entry_pb2.RunMetadataEntry]: ...
    def __init__(self,
        *,
        run_id: typing.Optional[api.ids_pb2.RunId] = ...,
        entries: typing.Optional[typing.Iterable[api.entity.run_metadata_entry_pb2.RunMetadataEntry]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["run_id",b"run_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries",b"entries","run_id",b"run_id"]) -> None: ...
global___RunMetadata = RunMetadata
