# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/tier_config_view.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.api.value import tier_type_pb2 as api_dot_value_dot_tier__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!api/entity/tier_config_view.proto\x12\x03\x61pi\x1a\x19\x61pi/value/tier_type.proto\"l\n\x0eTierConfigView\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x04type\x18\x02 \x01(\x0e\x32\r.api.TierType\x12\x17\n\x0fmax_active_runs\x18\x03 \x01(\x05\x12\x16\n\x0emax_membership\x18\x04 \x01(\x05\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_TIERCONFIGVIEW = DESCRIPTOR.message_types_by_name['TierConfigView']
TierConfigView = _reflection.GeneratedProtocolMessageType('TierConfigView', (_message.Message,), {
  'DESCRIPTOR' : _TIERCONFIGVIEW,
  '__module__' : 'api.entity.tier_config_view_pb2'
  # @@protoc_insertion_point(class_scope:api.TierConfigView)
  })
_sym_db.RegisterMessage(TierConfigView)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _TIERCONFIGVIEW._serialized_start=69
  _TIERCONFIGVIEW._serialized_end=177
# @@protoc_insertion_point(module_scope)
