
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-19T18:16:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2033a46079df647e1a2ab8b814f81670b109d6bf",
 "version": "0.2.28.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
