
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-19T16:28:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f24bd61c767f69fb4bd134636359faae46265e0",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
