"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ProbeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ProbeRequest = ProbeRequest

class ProbeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _ServiceStatus:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ServiceStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProbeResponse._ServiceStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SERVICE_STATUS_INVALID: ProbeResponse._ServiceStatus.ValueType  # 0
        SERVICE_STATUS_HEALTHY: ProbeResponse._ServiceStatus.ValueType  # 1
        SERVICE_STATUS_UNHEALTHY: ProbeResponse._ServiceStatus.ValueType  # 2
    class ServiceStatus(_ServiceStatus, metaclass=_ServiceStatusEnumTypeWrapper):
        pass

    SERVICE_STATUS_INVALID: ProbeResponse.ServiceStatus.ValueType  # 0
    SERVICE_STATUS_HEALTHY: ProbeResponse.ServiceStatus.ValueType  # 1
    SERVICE_STATUS_UNHEALTHY: ProbeResponse.ServiceStatus.ValueType  # 2

    STATUS_FIELD_NUMBER: builtins.int
    status: global___ProbeResponse.ServiceStatus.ValueType
    def __init__(self,
        *,
        status: global___ProbeResponse.ServiceStatus.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["status",b"status"]) -> None: ...
global___ProbeResponse = ProbeResponse
