
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-09-20T18:54:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "09214ba744ed3ab9df5c457b5c726a51305656b8",
 "version": "2.4.0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
