
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-23T23:17:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecd9e6f0819735ad0806033e295c7d934209254c",
 "version": "0.28.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
