# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/aws_credentials.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61pi/value/aws_credentials.proto\x12\x03\x61pi\"Y\n\x0e\x41wsCredentials\x12\x15\n\raccess_key_id\x18\x01 \x01(\t\x12\x19\n\x11secret_access_key\x18\x02 \x01(\t\x12\x15\n\rsession_token\x18\x03 \x01(\tB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_AWSCREDENTIALS = DESCRIPTOR.message_types_by_name['AwsCredentials']
AwsCredentials = _reflection.GeneratedProtocolMessageType('AwsCredentials', (_message.Message,), {
  'DESCRIPTOR' : _AWSCREDENTIALS,
  '__module__' : 'api.value.aws_credentials_pb2'
  # @@protoc_insertion_point(class_scope:api.AwsCredentials)
  })
_sym_db.RegisterMessage(AwsCredentials)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _AWSCREDENTIALS._serialized_start=40
  _AWSCREDENTIALS._serialized_end=129
# @@protoc_insertion_point(module_scope)
