# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/credit_log_event_v2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.api.entity import activity_wrapper_pb2 as api_dot_entity_dot_activity__wrapper__pb2
from layerapi.api.value import big_decimal_pb2 as api_dot_value_dot_big__decimal__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#api/value/credit_log_event_v2.proto\x12\x03\x61pi\x1a!api/entity/activity_wrapper.proto\x1a\x1b\x61pi/value/big_decimal.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n\x10\x43reditLogEventV2\x12.\n\nstart_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bupdate_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\rbalance_after\x18\x03 \x01(\x0b\x32\x0f.api.BigDecimal\x12%\n\x0c\x62\x61lance_used\x18\x04 \x01(\x0b\x32\x0f.api.BigDecimal\x12,\n\x06reason\x18\x05 \x01(\x0b\x32\x1c.api.CreditLogEventV2.Reason\x12\x1f\n\x17\x62\x61lance_after_as_string\x18\x06 \x01(\t\x12\x1e\n\x16\x62\x61lance_used_as_string\x18\x07 \x01(\t\x1aR\n\x06Reason\x12?\n\x18\x66\x61\x62ric_activity_snapshot\x18\x01 \x01(\x0b\x32\x1b.api.FabricActivitySnapshotH\x00\x42\x07\n\x05value\"\xc1\x01\n\x16\x46\x61\x62ricActivitySnapshot\x12.\n\x10\x61\x63tivity_wrapper\x18\x01 \x01(\x0b\x32\x14.api.ActivityWrapper\x12\x0e\n\x06\x66\x61\x62ric\x18\x02 \x01(\t\x12\x34\n\x11reported_duration\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x31\n\rreported_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_CREDITLOGEVENTV2 = DESCRIPTOR.message_types_by_name['CreditLogEventV2']
_CREDITLOGEVENTV2_REASON = _CREDITLOGEVENTV2.nested_types_by_name['Reason']
_FABRICACTIVITYSNAPSHOT = DESCRIPTOR.message_types_by_name['FabricActivitySnapshot']
CreditLogEventV2 = _reflection.GeneratedProtocolMessageType('CreditLogEventV2', (_message.Message,), {

  'Reason' : _reflection.GeneratedProtocolMessageType('Reason', (_message.Message,), {
    'DESCRIPTOR' : _CREDITLOGEVENTV2_REASON,
    '__module__' : 'api.value.credit_log_event_v2_pb2'
    # @@protoc_insertion_point(class_scope:api.CreditLogEventV2.Reason)
    })
  ,
  'DESCRIPTOR' : _CREDITLOGEVENTV2,
  '__module__' : 'api.value.credit_log_event_v2_pb2'
  # @@protoc_insertion_point(class_scope:api.CreditLogEventV2)
  })
_sym_db.RegisterMessage(CreditLogEventV2)
_sym_db.RegisterMessage(CreditLogEventV2.Reason)

FabricActivitySnapshot = _reflection.GeneratedProtocolMessageType('FabricActivitySnapshot', (_message.Message,), {
  'DESCRIPTOR' : _FABRICACTIVITYSNAPSHOT,
  '__module__' : 'api.value.credit_log_event_v2_pb2'
  # @@protoc_insertion_point(class_scope:api.FabricActivitySnapshot)
  })
_sym_db.RegisterMessage(FabricActivitySnapshot)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _CREDITLOGEVENTV2._serialized_start=174
  _CREDITLOGEVENTV2._serialized_end=563
  _CREDITLOGEVENTV2_REASON._serialized_start=481
  _CREDITLOGEVENTV2_REASON._serialized_end=563
  _FABRICACTIVITYSNAPSHOT._serialized_start=566
  _FABRICACTIVITYSNAPSHOT._serialized_end=759
# @@protoc_insertion_point(module_scope)
