# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/logged_data_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n api/value/logged_data_type.proto\x12\x03\x61pi*\xcd\x02\n\x0eLoggedDataType\x12\x1c\n\x18LOGGED_DATA_TYPE_INVALID\x10\x00\x12\x19\n\x15LOGGED_DATA_TYPE_TEXT\x10\x01\x12\x1a\n\x16LOGGED_DATA_TYPE_TABLE\x10\x02\x12\x19\n\x15LOGGED_DATA_TYPE_BLOB\x10\x03\x12\x1b\n\x17LOGGED_DATA_TYPE_NUMBER\x10\x04\x12\x1c\n\x18LOGGED_DATA_TYPE_BOOLEAN\x10\x05\x12\x1a\n\x16LOGGED_DATA_TYPE_IMAGE\x10\x06\x12\x1a\n\x16LOGGED_DATA_TYPE_VIDEO\x10\x07\x12\x1d\n\x19LOGGED_DATA_TYPE_MARKDOWN\x10\x08\x12\x19\n\x15LOGGED_DATA_TYPE_FILE\x10\t\x12\x1e\n\x1aLOGGED_DATA_TYPE_DIRECTORY\x10\nB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')

_LOGGEDDATATYPE = DESCRIPTOR.enum_types_by_name['LoggedDataType']
LoggedDataType = enum_type_wrapper.EnumTypeWrapper(_LOGGEDDATATYPE)
LOGGED_DATA_TYPE_INVALID = 0
LOGGED_DATA_TYPE_TEXT = 1
LOGGED_DATA_TYPE_TABLE = 2
LOGGED_DATA_TYPE_BLOB = 3
LOGGED_DATA_TYPE_NUMBER = 4
LOGGED_DATA_TYPE_BOOLEAN = 5
LOGGED_DATA_TYPE_IMAGE = 6
LOGGED_DATA_TYPE_VIDEO = 7
LOGGED_DATA_TYPE_MARKDOWN = 8
LOGGED_DATA_TYPE_FILE = 9
LOGGED_DATA_TYPE_DIRECTORY = 10


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _LOGGEDDATATYPE._serialized_start=42
  _LOGGEDDATATYPE._serialized_end=375
# @@protoc_insertion_point(module_scope)
