# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/python_source.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.api.value import language_version_pb2 as api_dot_value_dot_language__version__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pi/value/python_source.proto\x12\x03\x61pi\x1a api/value/language_version.proto\"x\n\x0cPythonSource\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x12\n\nentrypoint\x18\x02 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x03 \x01(\t\x12.\n\x10language_version\x18\x04 \x01(\x0b\x32\x14.api.LanguageVersionB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_PYTHONSOURCE = DESCRIPTOR.message_types_by_name['PythonSource']
PythonSource = _reflection.GeneratedProtocolMessageType('PythonSource', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONSOURCE,
  '__module__' : 'api.value.python_source_pb2'
  # @@protoc_insertion_point(class_scope:api.PythonSource)
  })
_sym_db.RegisterMessage(PythonSource)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _PYTHONSOURCE._serialized_start=72
  _PYTHONSOURCE._serialized_end=192
# @@protoc_insertion_point(module_scope)
