# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from layerapi.api.service.test import test_api_pb2 as api_dot_service_dot_test_dot_test__api__pb2


class TestAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FooMethod = channel.unary_unary(
                '/api.TestAPI/FooMethod',
                request_serializer=api_dot_service_dot_test_dot_test__api__pb2.FooMethodRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_test_dot_test__api__pb2.FooMethodResponse.FromString,
                )


class TestAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FooMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FooMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.FooMethod,
                    request_deserializer=api_dot_service_dot_test_dot_test__api__pb2.FooMethodRequest.FromString,
                    response_serializer=api_dot_service_dot_test_dot_test__api__pb2.FooMethodResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.TestAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FooMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.TestAPI/FooMethod',
            api_dot_service_dot_test_dot_test__api__pb2.FooMethodRequest.SerializeToString,
            api_dot_service_dot_test_dot_test__api__pb2.FooMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
