# Generated by Django 4.0.4 on 2022-09-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0007_auto_20200318_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
