
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-25T11:01:03+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5cf77bfc57fde60e14c1aa59566bb2eb4404bdb4",
 "version": "2022.09.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
