"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.value.docker_context_pb2
import layerapi.api.value.dockerfile_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class DockerEnvironment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOCKERFILE_FIELD_NUMBER: builtins.int
    DOCKER_CONTEXT_FIELD_NUMBER: builtins.int
    @property
    def dockerfile(self) -> api.value.dockerfile_pb2.Dockerfile: ...
    @property
    def docker_context(self) -> api.value.docker_context_pb2.DockerContext: ...
    def __init__(self,
        *,
        dockerfile: typing.Optional[api.value.dockerfile_pb2.Dockerfile] = ...,
        docker_context: typing.Optional[api.value.docker_context_pb2.DockerContext] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["docker_context",b"docker_context","dockerfile",b"dockerfile"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["docker_context",b"docker_context","dockerfile",b"dockerfile"]) -> None: ...
global___DockerEnvironment = DockerEnvironment
