# coding: utf-8

"""
    SYSNET RUIAN services API

    SYSNET RÚIAN service REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ruian
from ruian.models.polygon_jtsk import PolygonJtsk  # noqa: E501
from ruian.rest import ApiException


class TestPolygonJtsk(unittest.TestCase):
    """PolygonJtsk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolygonJtsk(self):
        """Test PolygonJtsk"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ruian.models.polygon_jtsk.PolygonJtsk()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
