VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('22')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('58')
MAJOR_VERSION = 0
MINOR_VERSION = 12
PATCH_VERSION = 202209220858
version_date = '2022/09/22 08:58'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
