# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/entity_version.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61pi/value/entity_version.proto\x12\x03\x61pi\x1a\x17validate/validate.proto\"*\n\rEntityVersion\x12\x19\n\x05value\x18\x01 \x01(\tB\n\xfa\x42\x07r\x05\x10\x01\x18\x80\x01\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_ENTITYVERSION = DESCRIPTOR.message_types_by_name['EntityVersion']
EntityVersion = _reflection.GeneratedProtocolMessageType('EntityVersion', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYVERSION,
  '__module__' : 'api.value.entity_version_pb2'
  # @@protoc_insertion_point(class_scope:api.EntityVersion)
  })
_sym_db.RegisterMessage(EntityVersion)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _ENTITYVERSION.fields_by_name['value']._options = None
  _ENTITYVERSION.fields_by_name['value']._serialized_options = b'\372B\007r\005\020\001\030\200\001'
  _ENTITYVERSION._serialized_start=64
  _ENTITYVERSION._serialized_end=106
# @@protoc_insertion_point(module_scope)
