"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class LanguageVersion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MAJOR_FIELD_NUMBER: builtins.int
    MINOR_FIELD_NUMBER: builtins.int
    MICRO_FIELD_NUMBER: builtins.int
    major: builtins.int
    minor: builtins.int
    micro: builtins.int
    def __init__(self,
        *,
        major: builtins.int = ...,
        minor: builtins.int = ...,
        micro: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["major",b"major","micro",b"micro","minor",b"minor"]) -> None: ...
global___LanguageVersion = LanguageVersion
