# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/query_filter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pi/value/query_filter.proto\x12\x03\x61pi\x1a\x17validate/validate.proto\"W\n\x06\x46ilter\x12\x16\n\x05\x66ield\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12%\n\x08operator\x18\x02 \x01(\x0e\x32\x13.api.FilterOperator\x12\x0e\n\x06values\x18\x03 \x03(\t*\x99\x03\n\x0e\x46ilterOperator\x12\x1b\n\x17\x46ILTER_OPERATOR_INVALID\x10\x00\x12\x19\n\x15\x46ILTER_OPERATOR_EXACT\x10\x01\x12\x1a\n\x16\x46ILTER_OPERATOR_IEXACT\x10\x02\x12\x1c\n\x18\x46ILTER_OPERATOR_CONTAINS\x10\x03\x12\x1d\n\x19\x46ILTER_OPERATOR_ICONTAINS\x10\x04\x12\x16\n\x12\x46ILTER_OPERATOR_IN\x10\x05\x12\x16\n\x12\x46ILTER_OPERATOR_GT\x10\x06\x12\x17\n\x13\x46ILTER_OPERATOR_GTE\x10\x07\x12\x16\n\x12\x46ILTER_OPERATOR_LT\x10\x08\x12\x17\n\x13\x46ILTER_OPERATOR_LTE\x10\t\x12\x1e\n\x1a\x46ILTER_OPERATOR_STARTSWITH\x10\n\x12\x1f\n\x1b\x46ILTER_OPERATOR_ISTARTSWITH\x10\x0b\x12\x1c\n\x18\x46ILTER_OPERATOR_ENDSWITH\x10\x0c\x12\x1d\n\x19\x46ILTER_OPERATOR_IENDSWITH\x10\rB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')

_FILTEROPERATOR = DESCRIPTOR.enum_types_by_name['FilterOperator']
FilterOperator = enum_type_wrapper.EnumTypeWrapper(_FILTEROPERATOR)
FILTER_OPERATOR_INVALID = 0
FILTER_OPERATOR_EXACT = 1
FILTER_OPERATOR_IEXACT = 2
FILTER_OPERATOR_CONTAINS = 3
FILTER_OPERATOR_ICONTAINS = 4
FILTER_OPERATOR_IN = 5
FILTER_OPERATOR_GT = 6
FILTER_OPERATOR_GTE = 7
FILTER_OPERATOR_LT = 8
FILTER_OPERATOR_LTE = 9
FILTER_OPERATOR_STARTSWITH = 10
FILTER_OPERATOR_ISTARTSWITH = 11
FILTER_OPERATOR_ENDSWITH = 12
FILTER_OPERATOR_IENDSWITH = 13


_FILTER = DESCRIPTOR.message_types_by_name['Filter']
Filter = _reflection.GeneratedProtocolMessageType('Filter', (_message.Message,), {
  'DESCRIPTOR' : _FILTER,
  '__module__' : 'api.value.query_filter_pb2'
  # @@protoc_insertion_point(class_scope:api.Filter)
  })
_sym_db.RegisterMessage(Filter)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _FILTER.fields_by_name['field']._options = None
  _FILTER.fields_by_name['field']._serialized_options = b'\372B\004r\002\020\001'
  _FILTEROPERATOR._serialized_start=152
  _FILTEROPERATOR._serialized_end=561
  _FILTER._serialized_start=62
  _FILTER._serialized_end=149
# @@protoc_insertion_point(module_scope)
