# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.api.value import schema_column_pb2 as api_dot_value_dot_schema__column__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi/value/schema.proto\x12\x03\x61pi\x1a\x1d\x61pi/value/schema_column.proto\",\n\x06Schema\x12\"\n\x07\x63olumns\x18\x01 \x03(\x0b\x32\x11.api.SchemaColumnB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_SCHEMA = DESCRIPTOR.message_types_by_name['Schema']
Schema = _reflection.GeneratedProtocolMessageType('Schema', (_message.Message,), {
  'DESCRIPTOR' : _SCHEMA,
  '__module__' : 'api.value.schema_pb2'
  # @@protoc_insertion_point(class_scope:api.Schema)
  })
_sym_db.RegisterMessage(Schema)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _SCHEMA._serialized_start=62
  _SCHEMA._serialized_end=106
# @@protoc_insertion_point(module_scope)
