# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/sha256.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi/value/sha256.proto\x12\x03\x61pi\x1a\x17validate/validate.proto\"1\n\x06Sha256\x12\'\n\x05value\x18\x03 \x01(\tB\x18\xfa\x42\x15r\x13\x32\x11^[A-Fa-f0-9]{64}$B\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_SHA256 = DESCRIPTOR.message_types_by_name['Sha256']
Sha256 = _reflection.GeneratedProtocolMessageType('Sha256', (_message.Message,), {
  'DESCRIPTOR' : _SHA256,
  '__module__' : 'api.value.sha256_pb2'
  # @@protoc_insertion_point(class_scope:api.Sha256)
  })
_sym_db.RegisterMessage(Sha256)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _SHA256.fields_by_name['value']._options = None
  _SHA256.fields_by_name['value']._serialized_options = b'\372B\025r\0232\021^[A-Fa-f0-9]{64}$'
  _SHA256._serialized_start=56
  _SHA256._serialized_end=105
# @@protoc_insertion_point(module_scope)
