# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/source_code.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pi/value/source_code.proto\x12\x03\x61pi\"\xf4\x02\n\nSourceCode\x12\x31\n\x11local_file_source\x18\x01 \x01(\x0b\x32\x14.api.LocalFileSourceH\x00\x12\x37\n\x14remote_file_location\x18\x02 \x01(\x0b\x32\x17.api.RemoteFileLocationH\x00\x12*\n\x08language\x18\x03 \x01(\x0e\x32\x18.api.SourceCode.Language\x12\x39\n\x10language_version\x18\x04 \x01(\x0b\x32\x1f.api.SourceCode.LanguageVersion\x1a>\n\x0fLanguageVersion\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05micro\x18\x03 \x01(\x05\"I\n\x08Language\x12\x14\n\x10LANGUAGE_INVALID\x10\x00\x12\x13\n\x0fLANGUAGE_PYTHON\x10\x01\x12\x12\n\x0eLANGUAGE_SCALA\x10\x02\x42\x08\n\x06source\"/\n\x0fLocalFileSource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\"4\n\x12RemoteFileLocation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\tB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_SOURCECODE = DESCRIPTOR.message_types_by_name['SourceCode']
_SOURCECODE_LANGUAGEVERSION = _SOURCECODE.nested_types_by_name['LanguageVersion']
_LOCALFILESOURCE = DESCRIPTOR.message_types_by_name['LocalFileSource']
_REMOTEFILELOCATION = DESCRIPTOR.message_types_by_name['RemoteFileLocation']
_SOURCECODE_LANGUAGE = _SOURCECODE.enum_types_by_name['Language']
SourceCode = _reflection.GeneratedProtocolMessageType('SourceCode', (_message.Message,), {

  'LanguageVersion' : _reflection.GeneratedProtocolMessageType('LanguageVersion', (_message.Message,), {
    'DESCRIPTOR' : _SOURCECODE_LANGUAGEVERSION,
    '__module__' : 'api.value.source_code_pb2'
    # @@protoc_insertion_point(class_scope:api.SourceCode.LanguageVersion)
    })
  ,
  'DESCRIPTOR' : _SOURCECODE,
  '__module__' : 'api.value.source_code_pb2'
  # @@protoc_insertion_point(class_scope:api.SourceCode)
  })
_sym_db.RegisterMessage(SourceCode)
_sym_db.RegisterMessage(SourceCode.LanguageVersion)

LocalFileSource = _reflection.GeneratedProtocolMessageType('LocalFileSource', (_message.Message,), {
  'DESCRIPTOR' : _LOCALFILESOURCE,
  '__module__' : 'api.value.source_code_pb2'
  # @@protoc_insertion_point(class_scope:api.LocalFileSource)
  })
_sym_db.RegisterMessage(LocalFileSource)

RemoteFileLocation = _reflection.GeneratedProtocolMessageType('RemoteFileLocation', (_message.Message,), {
  'DESCRIPTOR' : _REMOTEFILELOCATION,
  '__module__' : 'api.value.source_code_pb2'
  # @@protoc_insertion_point(class_scope:api.RemoteFileLocation)
  })
_sym_db.RegisterMessage(RemoteFileLocation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _SOURCECODE._serialized_start=37
  _SOURCECODE._serialized_end=409
  _SOURCECODE_LANGUAGEVERSION._serialized_start=262
  _SOURCECODE_LANGUAGEVERSION._serialized_end=324
  _SOURCECODE_LANGUAGE._serialized_start=326
  _SOURCECODE_LANGUAGE._serialized_end=399
  _LOCALFILESOURCE._serialized_start=411
  _LOCALFILESOURCE._serialized_end=458
  _REMOTEFILELOCATION._serialized_start=460
  _REMOTEFILELOCATION._serialized_end=512
# @@protoc_insertion_point(module_scope)
