# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/year_month.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pi/value/year_month.proto\x12\x03\x61pi\x1a\x17validate/validate.proto\"@\n\tYearMonth\x12\x19\n\x04year\x18\x01 \x01(\x05\x42\x0b\xfa\x42\x08\x1a\x06\x18\xb8\x17(\xb2\x0f\x12\x18\n\x05month\x18\x02 \x01(\x05\x42\t\xfa\x42\x06\x1a\x04\x18\x0c(\x01\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_YEARMONTH = DESCRIPTOR.message_types_by_name['YearMonth']
YearMonth = _reflection.GeneratedProtocolMessageType('YearMonth', (_message.Message,), {
  'DESCRIPTOR' : _YEARMONTH,
  '__module__' : 'api.value.year_month_pb2'
  # @@protoc_insertion_point(class_scope:api.YearMonth)
  })
_sym_db.RegisterMessage(YearMonth)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _YEARMONTH.fields_by_name['year']._options = None
  _YEARMONTH.fields_by_name['year']._serialized_options = b'\372B\010\032\006\030\270\027(\262\017'
  _YEARMONTH.fields_by_name['month']._options = None
  _YEARMONTH.fields_by_name['month']._serialized_options = b'\372B\006\032\004\030\014(\001'
  _YEARMONTH._serialized_start=60
  _YEARMONTH._serialized_end=124
# @@protoc_insertion_point(module_scope)
