VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('24')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('59')
MAJOR_VERSION = 0
MINOR_VERSION = 13
PATCH_VERSION = 202209241559
version_date = '2022/09/24 15:59'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
