# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from layerapi.api.service.account import account_api_pb2 as api_dot_service_dot_account_dot_account__api__pb2


class AccountAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccounts = channel.unary_unary(
                '/api.AccountAPI/GetAccounts',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountsRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountsResponse.FromString,
                )
        self.GetAccountViewByName = channel.unary_unary(
                '/api.AccountAPI/GetAccountViewByName',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameResponse.FromString,
                )
        self.GetAccountViewById = channel.unary_unary(
                '/api.AccountAPI/GetAccountViewById',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdResponse.FromString,
                )
        self.GetAccountByName = channel.unary_unary(
                '/api.AccountAPI/GetAccountByName',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountByNameRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountByNameResponse.FromString,
                )
        self.GetAccountById = channel.unary_unary(
                '/api.AccountAPI/GetAccountById',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountByIdRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountByIdResponse.FromString,
                )
        self.GetMyAccountView = channel.unary_unary(
                '/api.AccountAPI/GetMyAccountView',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewResponse.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/api.AccountAPI/CreateAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateAccountResponse.FromString,
                )
        self.UpdateAccount = channel.unary_unary(
                '/api.AccountAPI/UpdateAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.UpdateAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.UpdateAccountResponse.FromString,
                )
        self.DeleteAccount = channel.unary_unary(
                '/api.AccountAPI/DeleteAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountResponse.FromString,
                )
        self.DeleteAccountByName = channel.unary_unary(
                '/api.AccountAPI/DeleteAccountByName',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountByNameRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountByNameResponse.FromString,
                )
        self.CreateOrganizationAccount = channel.unary_unary(
                '/api.AccountAPI/CreateOrganizationAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountResponse.FromString,
                )
        self.CreateApiKey = channel.unary_unary(
                '/api.AccountAPI/CreateApiKey',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyResponse.FromString,
                )
        self.ToggleDatasetLikeByMyAccount = channel.unary_unary(
                '/api.AccountAPI/ToggleDatasetLikeByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountResponse.FromString,
                )
        self.GetDatasetLikedByMyAccount = channel.unary_unary(
                '/api.AccountAPI/GetDatasetLikedByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountResponse.FromString,
                )
        self.ToggleModelLikeByMyAccount = channel.unary_unary(
                '/api.AccountAPI/ToggleModelLikeByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountResponse.FromString,
                )
        self.GetModelLikedByMyAccount = channel.unary_unary(
                '/api.AccountAPI/GetModelLikedByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountResponse.FromString,
                )
        self.ToggleProjectLikeByMyAccount = channel.unary_unary(
                '/api.AccountAPI/ToggleProjectLikeByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountResponse.FromString,
                )
        self.GetProjectLikedByMyAccount = channel.unary_unary(
                '/api.AccountAPI/GetProjectLikedByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountResponse.FromString,
                )
        self.GetTierConfigByAccountId = channel.unary_unary(
                '/api.AccountAPI/GetTierConfigByAccountId',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetTierConfigByAccountIdRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetTierConfigByAccountIdResponse.FromString,
                )
        self.CreateTierConfigByAccountId = channel.unary_unary(
                '/api.AccountAPI/CreateTierConfigByAccountId',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateTierConfigByAccountIdRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateTierConfigByAccountIdResponse.FromString,
                )
        self.AssignTierToAccount = channel.unary_unary(
                '/api.AccountAPI/AssignTierToAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.AssignTierToAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.AssignTierToAccountResponse.FromString,
                )
        self.GetTiers = channel.unary_unary(
                '/api.AccountAPI/GetTiers',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetTiersRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetTiersResponse.FromString,
                )
        self.GetPermissionBuckets = channel.unary_unary(
                '/api.AccountAPI/GetPermissionBuckets',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetPermissionBucketsRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetPermissionBucketsResponse.FromString,
                )


class AccountAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountViewByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountViewById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyAccountView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccountByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrganizationAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleDatasetLikeByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetLikedByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleModelLikeByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelLikedByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleProjectLikeByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectLikedByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTierConfigByAccountId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTierConfigByAccountId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTierToAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTiers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPermissionBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccounts,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountsRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountsResponse.SerializeToString,
            ),
            'GetAccountViewByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountViewByName,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameResponse.SerializeToString,
            ),
            'GetAccountViewById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountViewById,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdResponse.SerializeToString,
            ),
            'GetAccountByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountByName,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountByNameRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountByNameResponse.SerializeToString,
            ),
            'GetAccountById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountById,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountByIdRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountByIdResponse.SerializeToString,
            ),
            'GetMyAccountView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyAccountView,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateAccountResponse.SerializeToString,
            ),
            'UpdateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.UpdateAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.UpdateAccountResponse.SerializeToString,
            ),
            'DeleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountResponse.SerializeToString,
            ),
            'DeleteAccountByName': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccountByName,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountByNameRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountByNameResponse.SerializeToString,
            ),
            'CreateOrganizationAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganizationAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountResponse.SerializeToString,
            ),
            'CreateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiKey,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyResponse.SerializeToString,
            ),
            'ToggleDatasetLikeByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleDatasetLikeByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountResponse.SerializeToString,
            ),
            'GetDatasetLikedByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetLikedByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountResponse.SerializeToString,
            ),
            'ToggleModelLikeByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleModelLikeByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountResponse.SerializeToString,
            ),
            'GetModelLikedByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelLikedByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountResponse.SerializeToString,
            ),
            'ToggleProjectLikeByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleProjectLikeByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountResponse.SerializeToString,
            ),
            'GetProjectLikedByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectLikedByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountResponse.SerializeToString,
            ),
            'GetTierConfigByAccountId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTierConfigByAccountId,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetTierConfigByAccountIdRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetTierConfigByAccountIdResponse.SerializeToString,
            ),
            'CreateTierConfigByAccountId': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTierConfigByAccountId,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateTierConfigByAccountIdRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateTierConfigByAccountIdResponse.SerializeToString,
            ),
            'AssignTierToAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTierToAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.AssignTierToAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.AssignTierToAccountResponse.SerializeToString,
            ),
            'GetTiers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTiers,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetTiersRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetTiersResponse.SerializeToString,
            ),
            'GetPermissionBuckets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPermissionBuckets,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetPermissionBucketsRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetPermissionBucketsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.AccountAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetAccounts',
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountsRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountViewByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetAccountViewByName',
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountViewById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetAccountViewById',
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetAccountByName',
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountByNameRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetAccountById',
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountByIdRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMyAccountView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetMyAccountView',
            api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/CreateAccount',
            api_dot_service_dot_account_dot_account__api__pb2.CreateAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.CreateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/UpdateAccount',
            api_dot_service_dot_account_dot_account__api__pb2.UpdateAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.UpdateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/DeleteAccount',
            api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAccountByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/DeleteAccountByName',
            api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountByNameRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.DeleteAccountByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateOrganizationAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/CreateOrganizationAccount',
            api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/CreateApiKey',
            api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToggleDatasetLikeByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/ToggleDatasetLikeByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDatasetLikedByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetDatasetLikedByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToggleModelLikeByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/ToggleModelLikeByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelLikedByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetModelLikedByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToggleProjectLikeByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/ToggleProjectLikeByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProjectLikedByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetProjectLikedByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTierConfigByAccountId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetTierConfigByAccountId',
            api_dot_service_dot_account_dot_account__api__pb2.GetTierConfigByAccountIdRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetTierConfigByAccountIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTierConfigByAccountId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/CreateTierConfigByAccountId',
            api_dot_service_dot_account_dot_account__api__pb2.CreateTierConfigByAccountIdRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.CreateTierConfigByAccountIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AssignTierToAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/AssignTierToAccount',
            api_dot_service_dot_account_dot_account__api__pb2.AssignTierToAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.AssignTierToAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTiers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetTiers',
            api_dot_service_dot_account_dot_account__api__pb2.GetTiersRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetTiersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPermissionBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetPermissionBuckets',
            api_dot_service_dot_account_dot_account__api__pb2.GetPermissionBucketsRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetPermissionBucketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
