"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _CreditActionCategory:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _CreditActionCategoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CreditActionCategory.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CREDIT_ACTION_CATEGORY_INVALID: _CreditActionCategory.ValueType  # 0
    CREDIT_ACTION_CATEGORY_ORCHESTRATION: _CreditActionCategory.ValueType  # 1
    CREDIT_ACTION_CATEGORY_RESOURCES: _CreditActionCategory.ValueType  # 2
    CREDIT_ACTION_CATEGORY_FUNDING: _CreditActionCategory.ValueType  # 3
    CREDIT_ACTION_CATEGORY_ALL: _CreditActionCategory.ValueType  # 4
class CreditActionCategory(_CreditActionCategory, metaclass=_CreditActionCategoryEnumTypeWrapper):
    pass

CREDIT_ACTION_CATEGORY_INVALID: CreditActionCategory.ValueType  # 0
CREDIT_ACTION_CATEGORY_ORCHESTRATION: CreditActionCategory.ValueType  # 1
CREDIT_ACTION_CATEGORY_RESOURCES: CreditActionCategory.ValueType  # 2
CREDIT_ACTION_CATEGORY_FUNDING: CreditActionCategory.ValueType  # 3
CREDIT_ACTION_CATEGORY_ALL: CreditActionCategory.ValueType  # 4
global___CreditActionCategory = CreditActionCategory

