"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LoggedDataXCoordinateType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _LoggedDataXCoordinateTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LoggedDataXCoordinateType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOGGED_DATA_X_COORDINATE_TYPE_INVALID: _LoggedDataXCoordinateType.ValueType  # 0
    LOGGED_DATA_X_COORDINATE_TYPE_STEP: _LoggedDataXCoordinateType.ValueType  # 1
    LOGGED_DATA_X_COORDINATE_TYPE_TIME: _LoggedDataXCoordinateType.ValueType  # 2
class LoggedDataXCoordinateType(_LoggedDataXCoordinateType, metaclass=_LoggedDataXCoordinateTypeEnumTypeWrapper):
    pass

LOGGED_DATA_X_COORDINATE_TYPE_INVALID: LoggedDataXCoordinateType.ValueType  # 0
LOGGED_DATA_X_COORDINATE_TYPE_STEP: LoggedDataXCoordinateType.ValueType  # 1
LOGGED_DATA_X_COORDINATE_TYPE_TIME: LoggedDataXCoordinateType.ValueType  # 2
global___LoggedDataXCoordinateType = LoggedDataXCoordinateType

