# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/value/monthly_credits_difference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.api.value import credit_action_category_pb2 as api_dot_value_dot_credit__action__category__pb2
from layerapi.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*api/value/monthly_credits_difference.proto\x12\x03\x61pi\x1a&api/value/credit_action_category.proto\x1a\x17validate/validate.proto\"\x87\x01\n\x18MonthlyCreditsDifference\x12\x1a\n\x12\x63redits_difference\x18\x01 \x01(\x03\x12\x18\n\x10usd_cents_amount\x18\x02 \x01(\x03\x12\x35\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\x19.api.CreditActionCategoryB\x08\xfa\x42\x05\x82\x01\x02\x10\x01\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_MONTHLYCREDITSDIFFERENCE = DESCRIPTOR.message_types_by_name['MonthlyCreditsDifference']
MonthlyCreditsDifference = _reflection.GeneratedProtocolMessageType('MonthlyCreditsDifference', (_message.Message,), {
  'DESCRIPTOR' : _MONTHLYCREDITSDIFFERENCE,
  '__module__' : 'api.value.monthly_credits_difference_pb2'
  # @@protoc_insertion_point(class_scope:api.MonthlyCreditsDifference)
  })
_sym_db.RegisterMessage(MonthlyCreditsDifference)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _MONTHLYCREDITSDIFFERENCE.fields_by_name['category']._options = None
  _MONTHLYCREDITSDIFFERENCE.fields_by_name['category']._serialized_options = b'\372B\005\202\001\002\020\001'
  _MONTHLYCREDITSDIFFERENCE._serialized_start=117
  _MONTHLYCREDITSDIFFERENCE._serialized_end=252
# @@protoc_insertion_point(module_scope)
