"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.value.metadata_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class StorageLocation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    URI_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    uri: typing.Text
    @property
    def metadata(self) -> api.value.metadata_pb2.Metadata: ...
    def __init__(self,
        *,
        uri: typing.Text = ...,
        metadata: typing.Optional[api.value.metadata_pb2.Metadata] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["metadata",b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["metadata",b"metadata","uri",b"uri"]) -> None: ...
global___StorageLocation = StorageLocation
