
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-19T09:52:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4304fa60979625450b79fe4cfb88426bc3d73e8",
 "version": "0.0.36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
