# flake8: noqa

"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.5.2"

# import ApiClient
from foxtail_trainer_api.api_client import ApiClient

# import Configuration
from foxtail_trainer_api.configuration import Configuration

# import exceptions
from foxtail_trainer_api.exceptions import OpenApiException
from foxtail_trainer_api.exceptions import ApiAttributeError
from foxtail_trainer_api.exceptions import ApiTypeError
from foxtail_trainer_api.exceptions import ApiValueError
from foxtail_trainer_api.exceptions import ApiKeyError
from foxtail_trainer_api.exceptions import ApiException
