
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-23T11:38:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a5bdd18a7d088c810892afc4d531e9aa8b6f1af",
 "version": "v22.12.00a220923"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
