# Generated by Django 4.1 on 2022-09-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationcheckpoint',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
