# Generated by Django 4.0.4 on 2022-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_organisationsubscription_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
