# Generated by Django 4.0.4 on 2022-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_branch_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationsubscription',
            name='cycle',
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='users',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
