
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-23T12:41:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3221687bff9d49e8b7c93a5a3c94192e1771d4ba",
 "version": "0.16.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
