"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LayerOrganizationRole:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _LayerOrganizationRoleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LayerOrganizationRole.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LAYER_ORGANIZATION_ROLE_INVALID: _LayerOrganizationRole.ValueType  # 0
    LAYER_ORGANIZATION_ROLE_READ: _LayerOrganizationRole.ValueType  # 1
    LAYER_ORGANIZATION_ROLE_WRITE: _LayerOrganizationRole.ValueType  # 2
    LAYER_ORGANIZATION_ROLE_ADMIN: _LayerOrganizationRole.ValueType  # 3
class LayerOrganizationRole(_LayerOrganizationRole, metaclass=_LayerOrganizationRoleEnumTypeWrapper):
    pass

LAYER_ORGANIZATION_ROLE_INVALID: LayerOrganizationRole.ValueType  # 0
LAYER_ORGANIZATION_ROLE_READ: LayerOrganizationRole.ValueType  # 1
LAYER_ORGANIZATION_ROLE_WRITE: LayerOrganizationRole.ValueType  # 2
LAYER_ORGANIZATION_ROLE_ADMIN: LayerOrganizationRole.ValueType  # 3
global___LayerOrganizationRole = LayerOrganizationRole

