"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.ids_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Organization(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.OrganizationId: ...
    name: typing.Text
    display_name: typing.Text
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.OrganizationId] = ...,
        name: typing.Text = ...,
        display_name: typing.Text = ...,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id","id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id","display_name",b"display_name","id",b"id","name",b"name"]) -> None: ...
global___Organization = Organization
