"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.ids_pb2
import layerapi.api.value.run_status_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Run(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _StatusOld:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _StatusOldEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Run._StatusOld.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATUS_INVALID: Run._StatusOld.ValueType  # 0
        STATUS_SCHEDULED: Run._StatusOld.ValueType  # 1
        STATUS_RUNNING: Run._StatusOld.ValueType  # 2
        STATUS_SUCCEEDED: Run._StatusOld.ValueType  # 3
        STATUS_FAILED: Run._StatusOld.ValueType  # 4
        STATUS_TERMINATED: Run._StatusOld.ValueType  # 5
    class StatusOld(_StatusOld, metaclass=_StatusOldEnumTypeWrapper):
        pass

    STATUS_INVALID: Run.StatusOld.ValueType  # 0
    STATUS_SCHEDULED: Run.StatusOld.ValueType  # 1
    STATUS_RUNNING: Run.StatusOld.ValueType  # 2
    STATUS_SUCCEEDED: Run.StatusOld.ValueType  # 3
    STATUS_FAILED: Run.StatusOld.ValueType  # 4
    STATUS_TERMINATED: Run.StatusOld.ValueType  # 5

    ID_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    CREATED_BY_ID_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CREATED_TIME_FIELD_NUMBER: builtins.int
    FINISHED_TIME_FIELD_NUMBER: builtins.int
    RUN_STATUS_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    PROJECT_NAME_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    STATUS_TIME_FIELD_NUMBER: builtins.int
    USER_COMMAND_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.RunId: ...
    @property
    def account_id(self) -> api.ids_pb2.AccountId: ...
    @property
    def project_id(self) -> api.ids_pb2.ProjectId: ...
    @property
    def created_by_id(self) -> api.ids_pb2.UserId: ...
    index: builtins.int
    name: typing.Text
    status: api.value.run_status_pb2.RunStatus.ValueType
    @property
    def created_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finished_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    run_status: global___Run.StatusOld.ValueType
    """deprecated"""

    info: typing.Text
    project_name: typing.Text
    @property
    def duration(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def status_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    user_command: typing.Text
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.RunId] = ...,
        account_id: typing.Optional[api.ids_pb2.AccountId] = ...,
        project_id: typing.Optional[api.ids_pb2.ProjectId] = ...,
        created_by_id: typing.Optional[api.ids_pb2.UserId] = ...,
        index: builtins.int = ...,
        name: typing.Text = ...,
        status: api.value.run_status_pb2.RunStatus.ValueType = ...,
        created_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        finished_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        run_status: global___Run.StatusOld.ValueType = ...,
        info: typing.Text = ...,
        project_name: typing.Text = ...,
        duration: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        status_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        user_command: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id",b"account_id","created_by_id",b"created_by_id","created_time",b"created_time","duration",b"duration","finished_time",b"finished_time","id",b"id","project_id",b"project_id","status_time",b"status_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id",b"account_id","created_by_id",b"created_by_id","created_time",b"created_time","duration",b"duration","finished_time",b"finished_time","id",b"id","index",b"index","info",b"info","name",b"name","project_id",b"project_id","project_name",b"project_name","run_status",b"run_status","status",b"status","status_time",b"status_time","user_command",b"user_command"]) -> None: ...
global___Run = Run
