# coding: utf-8

"""
    SYSNET RUIAN services API

    SYSNET RÚIAN service REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ruian
from ruian.models.zsj import Zsj  # noqa: E501
from ruian.rest import ApiException


class TestZsj(unittest.TestCase):
    """Zsj unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZsj(self):
        """Test Zsj"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ruian.models.zsj.Zsj()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
