# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/hello-nbdev',
                'doc_host': 'https://azaidi06.github.io',
                'git_url': 'https://github.com/azaidi06/hello-nbdev',
                'lib_path': 'hello_nbdev'},
  'syms': { 'hello_nbdev.core': { 'hello_nbdev.core.MeowSayer': ('core.html#meowsayer', 'hello_nbdev/core.py'),
                                  'hello_nbdev.core.MeowSayer.__init__': ('core.html#meowsayer.__init__', 'hello_nbdev/core.py'),
                                  'hello_nbdev.core.MeowSayer.say': ('core.html#meowsayer.say', 'hello_nbdev/core.py'),
                                  'hello_nbdev.core.say_meow': ('core.html#say_meow', 'hello_nbdev/core.py')}}}