
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-19T14:08:39+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "082f8130931a9ab25763166d98f4459b9fb22808",
 "version": "0.16.0a8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
