# Generated by Django 4.0.4 on 2022-06-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_delete_billingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationsubscription',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
        ),
    ]
