# Generated by Django 4.0.4 on 2022-06-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_rename_subscriptionprice_subscriptioncycle_and_more'),
        ('organisation', '0010_organisationsubscription_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscription',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_cycle', to='subscription.subscriptioncycle'),
        ),
    ]
