# Generated by Django 4.0.4 on 2022-06-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_remove_billingdetail_created_by_billingdetail_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingDetail',
        ),
    ]
