
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-20T17:29:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b038d6d57231b2d617cab591d96d94f031ae981",
 "version": "3.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
