# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['pipen_report']

package_data = \
{'': ['*'],
 'pipen_report': ['frontend/*',
                  'frontend/public/*',
                  'frontend/public/assets/*',
                  'frontend/src/*',
                  'frontend/src/components/*',
                  'frontend/src/components/DataTable/*',
                  'frontend/src/components/Image/*',
                  'frontend/src/components/PageNavButton/*',
                  'frontend/src/entries/*',
                  'frontend/src/layouts/*',
                  'frontend/src/pages/*']}

install_requires = \
['Markdown>=3.3,<4.0', 'cmdy>=0.5,<0.6', 'json5>=0.9,<0.10', 'pipen>=0.3,<0.4']

entry_points = \
{'pipen': ['report = pipen_report:PipenReport'],
 'pipen_cli': ['cli-report = pipen_report:PipenCliReport']}

setup_kwargs = {
    'name': 'pipen-report',
    'version': '0.4.5',
    'description': 'Report generation system for pipen',
    'long_description': '# pipen-report\n\nReport generation system for pipen\n\n## Installation\n\n```shell\n❯ pip install -U pipen-report\n\n# then update frontend dependencies:\n❯ pipen report update\n```\n\n## Enabling/Disabling the plugin\n\nThe plugin is registered via entrypoints. It\'s by default enabled. To disable it: `plugins=[..., "no:report"]`, or uninstall this plugin.\n\n## Example\n\nSee the pipeline in `example/`, and the reports generated by the pipeline:\n\nhttps://pwwang.github.io/pipen-report/example/output/REPORTS\n\n## Documentation\n\nSee: https://pwwang.github.io/pipen-report\n',
    'author': 'pwwang',
    'author_email': 'pwwang@pwwang.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/pwwang/pipen-report',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.7.1,<4.0.0',
}


setup(**setup_kwargs)
