
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-23T09:12:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "16741b9bf6d9b6744a9e8d10f8e77005282773f7",
 "version": "0.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
