from enum import Enum


class ProcessType(Enum):
    LOGIN_PATH_DETECTION = 1,
    MANUAL_SSO_DETECTION = 2,
    AUTOMATIC_SSO_DETECTION = 3,
    AUTOMATIC_SSO_DETECTION_BY_SEARCH_ENGINE = 4,
    PRIVACY_DETECTION = 5,
    SSO_SECURITY_ANALYSIS = 6

