
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-21T18:23:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a75b99d80651694506a05cb086a82c0d4232abdb",
 "version": "2.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
