# autogenerated
# mypy: ignore-errors
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secrets/secrets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15secrets/secrets.proto\x12\x04rime\x1a\x1bgoogle/protobuf/empty.proto\"1\n\x06Secret\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"2\n\x13\x43reateSecretRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"4\n\x14\x43reateSecretResponse\x12\x1c\n\x06secret\x18\x01 \x01(\x0b\x32\x0c.rime.Secret\"\x1f\n\x11ReadSecretRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x12ReadSecretResponse\x12\x1c\n\x06secret\x18\x01 \x01(\x0b\x32\x0c.rime.Secret\"!\n\x13\x44\x65leteSecretRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xda\x01\n\rSecretManager\x12\x45\n\x0c\x43reateSecret\x12\x19.rime.CreateSecretRequest\x1a\x1a.rime.CreateSecretResponse\x12\x41\n\x0c\x44\x65leteSecret\x12\x19.rime.DeleteSecretRequest\x1a\x16.google.protobuf.Empty\x12?\n\nReadSecret\x12\x17.rime.ReadSecretRequest\x1a\x18.rime.ReadSecretResponseB\x18Z\x16ri/_gen/protos/secretsb\x06proto3')



_SECRET = DESCRIPTOR.message_types_by_name['Secret']
_CREATESECRETREQUEST = DESCRIPTOR.message_types_by_name['CreateSecretRequest']
_CREATESECRETRESPONSE = DESCRIPTOR.message_types_by_name['CreateSecretResponse']
_READSECRETREQUEST = DESCRIPTOR.message_types_by_name['ReadSecretRequest']
_READSECRETRESPONSE = DESCRIPTOR.message_types_by_name['ReadSecretResponse']
_DELETESECRETREQUEST = DESCRIPTOR.message_types_by_name['DeleteSecretRequest']
Secret = _reflection.GeneratedProtocolMessageType('Secret', (_message.Message,), {
  'DESCRIPTOR' : _SECRET,
  '__module__' : 'rime_sdk.protos.secrets.secrets_pb2'
  # @@protoc_insertion_point(class_scope:rime.Secret)
  })
_sym_db.RegisterMessage(Secret)

CreateSecretRequest = _reflection.GeneratedProtocolMessageType('CreateSecretRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESECRETREQUEST,
  '__module__' : 'rime_sdk.protos.secrets.secrets_pb2'
  # @@protoc_insertion_point(class_scope:rime.CreateSecretRequest)
  })
_sym_db.RegisterMessage(CreateSecretRequest)

CreateSecretResponse = _reflection.GeneratedProtocolMessageType('CreateSecretResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESECRETRESPONSE,
  '__module__' : 'rime_sdk.protos.secrets.secrets_pb2'
  # @@protoc_insertion_point(class_scope:rime.CreateSecretResponse)
  })
_sym_db.RegisterMessage(CreateSecretResponse)

ReadSecretRequest = _reflection.GeneratedProtocolMessageType('ReadSecretRequest', (_message.Message,), {
  'DESCRIPTOR' : _READSECRETREQUEST,
  '__module__' : 'rime_sdk.protos.secrets.secrets_pb2'
  # @@protoc_insertion_point(class_scope:rime.ReadSecretRequest)
  })
_sym_db.RegisterMessage(ReadSecretRequest)

ReadSecretResponse = _reflection.GeneratedProtocolMessageType('ReadSecretResponse', (_message.Message,), {
  'DESCRIPTOR' : _READSECRETRESPONSE,
  '__module__' : 'rime_sdk.protos.secrets.secrets_pb2'
  # @@protoc_insertion_point(class_scope:rime.ReadSecretResponse)
  })
_sym_db.RegisterMessage(ReadSecretResponse)

DeleteSecretRequest = _reflection.GeneratedProtocolMessageType('DeleteSecretRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETESECRETREQUEST,
  '__module__' : 'rime_sdk.protos.secrets.secrets_pb2'
  # @@protoc_insertion_point(class_scope:rime.DeleteSecretRequest)
  })
_sym_db.RegisterMessage(DeleteSecretRequest)

_SECRETMANAGER = DESCRIPTOR.services_by_name['SecretManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026ri/_gen/protos/secrets'
  _SECRET._serialized_start=60
  _SECRET._serialized_end=109
  _CREATESECRETREQUEST._serialized_start=111
  _CREATESECRETREQUEST._serialized_end=161
  _CREATESECRETRESPONSE._serialized_start=163
  _CREATESECRETRESPONSE._serialized_end=215
  _READSECRETREQUEST._serialized_start=217
  _READSECRETREQUEST._serialized_end=248
  _READSECRETRESPONSE._serialized_start=250
  _READSECRETRESPONSE._serialized_end=300
  _DELETESECRETREQUEST._serialized_start=302
  _DELETESECRETREQUEST._serialized_end=335
  _SECRETMANAGER._serialized_start=338
  _SECRETMANAGER._serialized_end=556
# @@protoc_insertion_point(module_scope)
