# Generated by Django 4.0.4 on 2022-06-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_addon'),
        ('organisation', '0009_organisationsubscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscription',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='org_addons', to='subscription.addon'),
        ),
    ]
