# Generated by Django 4.0.4 on 2022-06-16 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0011_organisationsubscription_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetail',
            name='created_by',
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_billing_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
