# Generated by Django 4.0.4 on 2022-08-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_department_level_department_lft_department_rght_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'default_permissions': [], 'ordering': ['-created_at'], 'permissions': (('access_branch', 'Access'), ('detail_branch', 'View'), ('view_branch', 'List'), ('change_branch', 'Edit'), ('delete_branch', 'Delete'), ('add_branch', 'Create'))},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'default_permissions': [], 'ordering': ['-created_at'], 'permissions': (('access_department', 'Access'), ('detail_department', 'View'), ('view_department', 'List'), ('change_department', 'Edit'), ('delete_department', 'Delete'), ('add_department', 'Create'))},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'default_permissions': [], 'ordering': ['-created_at'], 'permissions': (('access_organisation', 'Access'), ('detail_organisation', 'View'), ('view_organisation', 'List'), ('change_organisation', 'Edit'), ('delete_organisation', 'Delete'), ('add_organisation', 'Create'))},
        ),
        migrations.AlterModelOptions(
            name='organisationsubscription',
            options={'default_permissions': [], 'ordering': ['-created_at'], 'permissions': (('access_organisationsubscription', 'Access'), ('detail_organisationsubscription', 'View'), ('view_organisationsubscription', 'List'), ('change_organisationsubscription', 'Edit'), ('delete_organisationsubscription', 'Delete'), ('add_organisationsubscription', 'Create'))},
        ),
    ]
