
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-23T14:10:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dbfcfa7029b4c352ed25b9e30f3f5dde0d71028",
 "version": "0.2.29.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
