
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-24T20:55:10+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd34ec8ae3e6108f277627d0f5d23a2126aa61cc",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
