"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.value.logged_data_type_pb2
import layerapi.api.value.logged_data_x_coordinate_type_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class LoggedData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Coordinate(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        X_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        x: builtins.int
        value: typing.Text
        def __init__(self,
            *,
            x: builtins.int = ...,
            value: typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["value",b"value","x",b"x"]) -> None: ...

    UNIQUE_TAG_FIELD_NUMBER: builtins.int
    GROUP_TAG_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    VALUES_WITH_COORDINATES_FIELD_NUMBER: builtins.int
    X_COORDINATE_TYPE_FIELD_NUMBER: builtins.int
    CREATED_TIME_FIELD_NUMBER: builtins.int
    UPDATED_TIME_FIELD_NUMBER: builtins.int
    unique_tag: typing.Text
    """unique_tag is unique across the entire dataset build or model train"""

    group_tag: typing.Text
    """group tag can be set to any string, and helps group data in the UI into a single chart"""

    category: typing.Text
    """category is a higher level grouping in the UI that helps filter data"""

    type: api.value.logged_data_type_pb2.LoggedDataType.ValueType
    value: typing.Text
    """For LoggedDataTypes BLOB, IMAGE, VIDEO, FILE, DIRECTORY this is the S3 URL to download.
    For logged data with coordinates, this field must be empty.
    """

    @property
    def values_with_coordinates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LoggedData.Coordinate]: ...
    x_coordinate_type: api.value.logged_data_x_coordinate_type_pb2.LoggedDataXCoordinateType.ValueType
    @property
    def created_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        unique_tag: typing.Text = ...,
        group_tag: typing.Text = ...,
        category: typing.Text = ...,
        type: api.value.logged_data_type_pb2.LoggedDataType.ValueType = ...,
        value: typing.Text = ...,
        values_with_coordinates: typing.Optional[typing.Iterable[global___LoggedData.Coordinate]] = ...,
        x_coordinate_type: api.value.logged_data_x_coordinate_type_pb2.LoggedDataXCoordinateType.ValueType = ...,
        created_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_time",b"created_time","updated_time",b"updated_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["category",b"category","created_time",b"created_time","group_tag",b"group_tag","type",b"type","unique_tag",b"unique_tag","updated_time",b"updated_time","value",b"value","values_with_coordinates",b"values_with_coordinates","x_coordinate_type",b"x_coordinate_type"]) -> None: ...
global___LoggedData = LoggedData
