# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/payment_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pi/entity/payment_info.proto\x12\x03\x61pi\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n\x0bPaymentInfo\x12\x30\n\x0c\x63reated_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x16\n\x0ereceipt_number\x18\x05 \x01(\t\x12\x13\n\x0breceipt_url\x18\x06 \x01(\tB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_PAYMENTINFO = DESCRIPTOR.message_types_by_name['PaymentInfo']
PaymentInfo = _reflection.GeneratedProtocolMessageType('PaymentInfo', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTINFO,
  '__module__' : 'api.entity.payment_info_pb2'
  # @@protoc_insertion_point(class_scope:api.PaymentInfo)
  })
_sym_db.RegisterMessage(PaymentInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _PAYMENTINFO._serialized_start=72
  _PAYMENTINFO._serialized_end=230
# @@protoc_insertion_point(module_scope)
