"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.entity.task_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class RunMetadataEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TASK_ID_FIELD_NUMBER: builtins.int
    TASK_TYPE_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    task_id: typing.Text
    task_type: api.entity.task_pb2.Task.Type.ValueType
    key: typing.Text
    value: typing.Text
    def __init__(self,
        *,
        task_id: typing.Text = ...,
        task_type: api.entity.task_pb2.Task.Type.ValueType = ...,
        key: typing.Text = ...,
        value: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key",b"key","task_id",b"task_id","task_type",b"task_type","value",b"value"]) -> None: ...
global___RunMetadataEntry = RunMetadataEntry
