# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/run_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layerapi.api.entity import run_metadata_entry_pb2 as api_dot_entity_dot_run__metadata__entry__pb2
from layerapi.api import ids_pb2 as api_dot_ids__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pi/entity/run_metadata.proto\x12\x03\x61pi\x1a#api/entity/run_metadata_entry.proto\x1a\rapi/ids.proto\"Q\n\x0bRunMetadata\x12\x1a\n\x06run_id\x18\x01 \x01(\x0b\x32\n.api.RunId\x12&\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x15.api.RunMetadataEntryB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_RUNMETADATA = DESCRIPTOR.message_types_by_name['RunMetadata']
RunMetadata = _reflection.GeneratedProtocolMessageType('RunMetadata', (_message.Message,), {
  'DESCRIPTOR' : _RUNMETADATA,
  '__module__' : 'api.entity.run_metadata_pb2'
  # @@protoc_insertion_point(class_scope:api.RunMetadata)
  })
_sym_db.RegisterMessage(RunMetadata)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _RUNMETADATA._serialized_start=90
  _RUNMETADATA._serialized_end=171
# @@protoc_insertion_point(module_scope)
