
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-19T08:14:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "84e69fc890434564757747fafc7646e54db6e14f",
 "version": "2.8.5.dev20220920"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
