
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-21T15:46:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3e173fd5dd72e2ba396503d9338f46a7a1dadb8",
 "version": "0.4.157"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
