
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-23T13:45:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d52e51da2c6e0c597f405efe4ca0e613d29b4b46",
 "version": "4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
