# Running the package on Henon map.
import numpy as np
import pandas as pd
import nlntest as nlt


# Example: Henon map
ahen=1.4
bhen=0.3 # Parameters of Hebnon map
y=np.zeros((1000,2))
y[0,0]=0
y[0,1]=0.9 # Henon map initial vallues
for t in range(1,1000):
 y[t,0]=1-ahen*y[t-1,0]**2+bhen*y[t-1,1]
 y[t,1]=y[t-1,0]
y=y+np.random.randn(1000,2)*0.5
print(' ')
print('     ' 'Example: Linearity test of time series generated by Henon map')
print(' ')
resultsMulti=nlt.nlntstmultv(y)
resultsAnn=nlt.annnlntst(y)

''' Since the Henon map is nonlinear, pvalues will be smaller than 0.05
in 95% of times that you run the modules '''

