# Generated by Django 4.0.4 on 2022-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_remove_organisationsubscription_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscription',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
