VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('20')
VERSION_HOUR = int('23')
VERSION_MINUTE = int('31')
MAJOR_VERSION = 1
MINOR_VERSION = 11
PATCH_VERSION = 202209202331
version_date = '2022/09/20 23:31'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
