# Generated by Django 2.2.26 on 2022-01-17 03:54

from django.conf import settings
from django.db import migrations

from tahoe_sites import zd_helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0007_historicalorganization'),
        ('tahoe_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userorganizationmapping',
            unique_together={
                zd_helpers.get_unique_together(('user', 'organization')),
            },
        ),
    ]
