
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-24T07:51:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9be7c857bbf9e866abbb1e370f925f8146da8bb2",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
