# Generated by Django 4.0 on 2022-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'ordering': ('-id',),
                'permissions': (('access_branch', 'Access'), ('detail_branch', 'View'), ('view_branch', 'List'), ('change_branch', 'Edit'), ('delete_branch', 'Delete'), ('add_branch', 'Create')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-id',),
                'permissions': (('access_department', 'Access'), ('detail_department', 'View'), ('view_department', 'List'), ('change_department', 'Edit'), ('delete_department', 'Delete'), ('add_department', 'Create')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OrganisationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-id',),
                'permissions': (('access_organisationsubscription', 'Access'), ('detail_organisationsubscription', 'View'), ('view_organisationsubscription', 'List'), ('change_organisationsubscription', 'Edit'), ('delete_organisationsubscription', 'Delete'), ('add_organisationsubscription', 'Create')),
                'default_permissions': [],
            },
        ),
    ]
