# Generated by Django 4.0.4 on 2022-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_alter_organisationsubscription_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
