
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-21T11:23:06-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2650603ff29e587020a4dceea39cc0b9d4d45da6",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
