# Generated by Django 4.1 on 2022-09-20 03:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationCheckpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('migrations', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
