# Generated by Django 4.1.1 on 2022-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demian_parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpopup',
            name='period',
            field=models.CharField(blank=True, help_text='공란 가능', max_length=40, null=True, verbose_name='행사기간'),
        ),
    ]
