# Generated by Django 4.1.1 on 2022-09-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demian_parts', '0003_type4_delete_eventpopup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type4',
            name='h2',
            field=models.TextField(help_text='줄넘기기 : br tag, 강조 : strong tag', verbose_name='h2'),
        ),
        migrations.AlterField(
            model_name='type4',
            name='h3',
            field=models.CharField(help_text='강조 : strong tag', max_length=20, verbose_name='h3'),
        ),
    ]
