# Generated by Django 4.1.1 on 2022-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demian_parts', '0005_remove_notipopup_popup_ptr_type4_activate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_title', models.CharField(blank=True, default='EVENT', max_length=20, verbose_name='modal_title')),
                ('h2', models.CharField(help_text='줄넘기기 : br tag', max_length=40, verbose_name='h1')),
                ('p', models.TextField(help_text='줄넘기기 : br tag, 강조 : strong tag', verbose_name='h2')),
                ('link_url', models.URLField(blank=True, help_text='공란 가능', verbose_name='link_url')),
                ('link_text', models.CharField(default='Book a Table', max_length=20, verbose_name='link_text')),
                ('link_video_url', models.URLField(blank=True, help_text='공란 가능', verbose_name='link_video_url')),
                ('link_video_text', models.CharField(default='Watch Video', max_length=20, verbose_name='link_video_text')),
                ('img', models.ImageField(upload_to='images/popup/type3')),
                ('activate', models.BooleanField(default=False, help_text='활성창 1개만 가능')),
            ],
        ),
        migrations.AddField(
            model_name='type4',
            name='modal_title',
            field=models.CharField(blank=True, default='EVENT', max_length=20, verbose_name='modal_title'),
        ),
        migrations.AlterField(
            model_name='type4',
            name='link_text',
            field=models.CharField(default='Get Started', max_length=20, verbose_name='link_text'),
        ),
        migrations.AlterField(
            model_name='type4',
            name='link_url',
            field=models.URLField(blank=True, help_text='공란 가능', verbose_name='link_url'),
        ),
    ]
