# Generated by Django 4.1.1 on 2022-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demian_parts', '0006_type3_type4_modal_title_alter_type4_link_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_title', models.CharField(blank=True, default='EVENT', max_length=20, verbose_name='modal_title')),
                ('h2', models.CharField(max_length=40, verbose_name='h2')),
                ('p', models.TextField(help_text='줄넘기기 : br tag, 강조 : strong tag', verbose_name='p')),
                ('link_url', models.URLField(blank=True, help_text='공란 가능', verbose_name='link_url')),
                ('link_text', models.CharField(default='Book a Table', max_length=20, verbose_name='link_text')),
                ('link_video_url', models.URLField(blank=True, help_text='공란 가능', verbose_name='link_video_url')),
                ('link_video_text', models.CharField(default='Watch Video', max_length=20, verbose_name='link_video_text')),
                ('bg', models.ImageField(upload_to='images/popup/type2')),
                ('activate', models.BooleanField(default=False, help_text='활성창 1개만 가능')),
            ],
        ),
        migrations.AlterField(
            model_name='type3',
            name='h2',
            field=models.CharField(help_text='줄넘기기 : br tag', max_length=40, verbose_name='h2'),
        ),
        migrations.AlterField(
            model_name='type3',
            name='p',
            field=models.TextField(help_text='줄넘기기 : br tag, 강조 : strong tag', verbose_name='p'),
        ),
    ]
