
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-23T09:18:26-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "77cedd9d3ac37d276a532167eef0435c1aa66e55",
 "version": "0.15.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
