# coding: utf-8

"""
    SYSNET RUIAN services API

    SYSNET RÚIAN service REST API  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NearbyAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order': 'int',
        'distance': 'float',
        'address': 'Address'
    }

    attribute_map = {
        'order': 'order',
        'distance': 'distance',
        'address': 'address'
    }

    def __init__(self, order=None, distance=None, address=None):  # noqa: E501
        """NearbyAddress - a model defined in Swagger"""  # noqa: E501
        self._order = None
        self._distance = None
        self._address = None
        self.discriminator = None
        if order is not None:
            self.order = order
        if distance is not None:
            self.distance = distance
        if address is not None:
            self.address = address

    @property
    def order(self):
        """Gets the order of this NearbyAddress.  # noqa: E501


        :return: The order of this NearbyAddress.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this NearbyAddress.


        :param order: The order of this NearbyAddress.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def distance(self):
        """Gets the distance of this NearbyAddress.  # noqa: E501


        :return: The distance of this NearbyAddress.  # noqa: E501
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """Sets the distance of this NearbyAddress.


        :param distance: The distance of this NearbyAddress.  # noqa: E501
        :type: float
        """

        self._distance = distance

    @property
    def address(self):
        """Gets the address of this NearbyAddress.  # noqa: E501


        :return: The address of this NearbyAddress.  # noqa: E501
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this NearbyAddress.


        :param address: The address of this NearbyAddress.  # noqa: E501
        :type: Address
        """

        self._address = address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NearbyAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NearbyAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
