
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-21T21:26:45-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6db99705aaf126252bc06a3ce1f994a864b63b82",
 "version": "v0.3.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
