
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-17T09:39:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6c67d7bc5bb0408a5a844ff63fcd0f75e1cd296",
 "version": "v0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
