# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/19_paper.figures.learning_curves.ipynb.

# %% auto 0
__all__ = ['plot_learning_curve']

# %% ../nbs/19_paper.figures.learning_curves.ipynb 20
def plot_learning_curve(x, losses_train, losses_valid, ax=None,  train_kwargs={}, valid_kwargs={}):
    if ax is None:
        ax = plt.gca()
    ax.plot(x, losses_train, label='Training', **train_kwargs) 
    #ax.plot(x, losses_valid, label='Validation', **valid_kwargs) 
    ax.set_yscale('log')
    ax.set_xscale('log')
    return(ax)
