# coding: utf-8

"""
    Datový konektor Domino pro eSMLOUVY

    Toto je datový konektor umožňující datovou výměnu mezi obchodní logikou aplikace eSMLOUVY a datovým serverem HCL Domino.  Ovládá se pomocí REST API   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DocumentAttachment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'storage': 'str',
        'id': 'str',
        'domino': 'DominoCommons'
    }

    attribute_map = {
        'name': 'name',
        'storage': 'storage',
        'id': 'id',
        'domino': 'domino'
    }

    def __init__(self, name=None, storage=None, id=None, domino=None):  # noqa: E501
        """DocumentAttachment - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._storage = None
        self._id = None
        self._domino = None
        self.discriminator = None
        if name is not None:
            self.name = name
        self.storage = storage
        self.id = id
        if domino is not None:
            self.domino = domino

    @property
    def name(self):
        """Gets the name of this DocumentAttachment.  # noqa: E501

        Attachment name for display  # noqa: E501

        :return: The name of this DocumentAttachment.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DocumentAttachment.

        Attachment name for display  # noqa: E501

        :param name: The name of this DocumentAttachment.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def storage(self):
        """Gets the storage of this DocumentAttachment.  # noqa: E501

        Replica ID storage application  # noqa: E501

        :return: The storage of this DocumentAttachment.  # noqa: E501
        :rtype: str
        """
        return self._storage

    @storage.setter
    def storage(self, storage):
        """Sets the storage of this DocumentAttachment.

        Replica ID storage application  # noqa: E501

        :param storage: The storage of this DocumentAttachment.  # noqa: E501
        :type: str
        """
        if storage is None:
            raise ValueError("Invalid value for `storage`, must not be `None`")  # noqa: E501

        self._storage = storage

    @property
    def id(self):
        """Gets the id of this DocumentAttachment.  # noqa: E501

        Attachment unique identifier  # noqa: E501

        :return: The id of this DocumentAttachment.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DocumentAttachment.

        Attachment unique identifier  # noqa: E501

        :param id: The id of this DocumentAttachment.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def domino(self):
        """Gets the domino of this DocumentAttachment.  # noqa: E501


        :return: The domino of this DocumentAttachment.  # noqa: E501
        :rtype: DominoCommons
        """
        return self._domino

    @domino.setter
    def domino(self, domino):
        """Sets the domino of this DocumentAttachment.


        :param domino: The domino of this DocumentAttachment.  # noqa: E501
        :type: DominoCommons
        """

        self._domino = domino

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentAttachment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentAttachment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
