# Running the package on logistic map 
import numpy as np
import pandas as pd
import nlntest as nlt

# Example: logistic map with additive noise
y=np.zeros((1000,1))
y[0,0]=0.1
for t in range(1,1000):
 y[t,0]=4*y[t-1,0]*(1-y[t-1,0])
y=y+np.random.randn(1000,1)*0.3
print(' ')
print('     ' 'Example: Linearity test of time series generated by the logistic map')
print(' ')
results=nlt.nlntstuniv(y)
resultsMulti=nlt.nlntstmultv(y)
resultsAnn=nlt.annnlntst(y)


''' Since the logistic map is nonlinear, pvalues will be smaller than 0.05
in 95% of times that you run the modules '''


