# Running package on univariate normal random numbers
import numpy as np
import pandas as pd
import nlntest as nlt

# Exapmle: normal random number which is an iid series
y=np.random.randn(1000,1)

print(' ')
print('Example: Linearity test of univariate time series generated by normal distribution')
print(' ')

results=nlt.nlntstuniv(y)
resultsMulti=nlt.nlntstmultv(y)
resultsAnn=nlt.annnlntst(y)

''' Since iid series are not dependent, pvalues will be greater than 0.05
in 95% of times that you run the modules'''


