
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-18T14:55:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f1c8e0365f488d9292cbfc6a2f53cd31e7f038c",
 "version": "1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
