# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/26_paper_cnn_lr_finder.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/26_paper_cnn_lr_finder.ipynb 3
from pathlib import Path
import pickle

# import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from ...data.loading import load_kssl
from ...data.selection import (select_y, select_tax_order, select_X)
from ...data.transform import log_transform_y
from ...data.torch import DataLoaders, SNV_transform
from ...training.cnn import (Model, weights_init)
from ...training.cnn import Learner

# Deep Learning stack
import torch
from torch.optim import Adam
from torch.nn import MSELoss

from fastcore.transform import compose

import warnings
warnings.filterwarnings('ignore')
