
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-22T01:51:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1df09a6e2e1367d28b02b8d452128b06144633ed",
 "version": "4.1.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
