# Generated by Django 4.1.1 on 2022-09-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demian_parts', '0002_alter_eventpopup_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3', models.CharField(help_text='강조 : <strong></strong>', max_length=20, verbose_name='h3')),
                ('h1', models.CharField(max_length=40, verbose_name='h1')),
                ('h2', models.TextField(help_text='줄넘기기 : <br>, 강조 : <strong></strong>', verbose_name='h2')),
                ('link_url', models.URLField(default='#', help_text='공란 가능', verbose_name='link_url')),
                ('link_text', models.CharField(max_length=20, verbose_name='link_text')),
                ('bg', models.ImageField(upload_to='images/popup/')),
            ],
        ),
        migrations.DeleteModel(
            name='EventPopup',
        ),
    ]
