# Generated by Django 4.1.1 on 2022-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demian_parts', '0004_alter_type4_h2_alter_type4_h3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notipopup',
            name='popup_ptr',
        ),
        migrations.AddField(
            model_name='type4',
            name='activate',
            field=models.BooleanField(default=False, help_text='활성창 1개만 가능'),
        ),
        migrations.AlterField(
            model_name='type4',
            name='bg',
            field=models.ImageField(upload_to='images/popup/type4'),
        ),
        migrations.DeleteModel(
            name='ImagePopup',
        ),
        migrations.DeleteModel(
            name='NotiPopup',
        ),
        migrations.DeleteModel(
            name='Popup',
        ),
    ]
