# Generated by Django 4.1.1 on 2022-09-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demian_parts', '0007_type2_alter_type3_h2_alter_type3_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_title', models.CharField(blank=True, default='EVENT', max_length=20, verbose_name='modal_title')),
                ('h2', models.CharField(max_length=40, verbose_name='h2')),
                ('p', models.TextField(help_text='줄넘기기 : br tag, 강조 : strong tag', verbose_name='p')),
                ('link_url', models.URLField(blank=True, help_text='공란 가능', verbose_name='link_url')),
                ('link_text', models.CharField(default='Get Started', max_length=20, verbose_name='link_text')),
                ('bg', models.ImageField(upload_to='images/popup/type1')),
                ('bg2', models.ImageField(null=True, upload_to='images/popup/type1')),
                ('bg3', models.ImageField(null=True, upload_to='images/popup/type1')),
                ('activate', models.BooleanField(default=False, help_text='활성창 1개만 가능')),
            ],
        ),
        migrations.AlterField(
            model_name='type2',
            name='link_text',
            field=models.CharField(default='Get Started', max_length=20, verbose_name='link_text'),
        ),
    ]
